INSERT INTO "my_catalog"."my_schema"."order_header" ("order_id","order_date","currency","order_status","order_lifecycle_event","subtotal","tax_total","shipping_total","discount_total","grand_total","customer_id","first_name","last_name","full_name","email","phone") VALUES ('ORD-88294-X','2023-10-27T14:30:00Z','USD','CREATED','order_created',475.0,35.6,15.0,-50.0,475.6,'CUST-4052','Alex','Smith','Alex Smith','alex.smith@example.com','+1-555-010-9988');
INSERT INTO "my_catalog"."my_schema"."order_item" ("order_id","line_number","sku","product_name","quantity","unit_price","line_total","item_type") VALUES ('ORD-88294-X',1,'SKU-SHIRT-BLUE-L','Premium Cotton Shirt - Blue/Large',3,55.0,165.0,'SINGLE');
INSERT INTO "my_catalog"."my_schema"."order_item" ("order_id","line_number","sku","product_name","quantity","unit_price","line_total","item_type") VALUES ('ORD-88294-X',2,'SKU-BNDL-GYM-SET','Fitness Starter Pack',2,120.0,240.0,'BUNDLE');
INSERT INTO "my_catalog"."my_schema"."order_item" ("order_id","line_number","sku","product_name","quantity","unit_price","line_total","item_type") VALUES ('ORD-88294-X',3,'SKU-WATCH-BLK','Midnight Edition Analog Watch',1,70.0,70.0,'SINGLE');
INSERT INTO "my_catalog"."my_schema"."order_item_component" ("order_id","line_number","sku","component_sku","component_name","quantity","internal_cost_allocation") VALUES ('ORD-88294-X',2,'SKU-BNDL-GYM-SET','SKU-MAT-01','Eco-Friendly Yoga Mat',2,70.0);
INSERT INTO "my_catalog"."my_schema"."order_item_component" ("order_id","line_number","sku","component_sku","component_name","quantity","internal_cost_allocation") VALUES ('ORD-88294-X',2,'SKU-BNDL-GYM-SET','SKU-BTL-05','Insulated Water Bottle',2,50.0);
INSERT INTO "my_catalog"."my_schema"."payment" ("payment_method","amount","payment_status","card_type","last_four","auth_code") VALUES ('CREDIT_CARD',425.6,'AUTHORIZED','MASTERCARD','1234','AUTH998822');
INSERT INTO "my_catalog"."my_schema"."payment" ("payment_method","amount","payment_status","coupon_code","promotion_id") VALUES ('DISCOUNT_COUPON',50.0,'APPLIED','BOGO50','BUNDLE_PROMO_2023');
INSERT INTO "my_catalog"."my_schema"."order_shipping" ("order_id","first_name","last_name","street","city","state","postal_code","country") VALUES ('ORD-88294-X','Alex','Smith','123 Maple Avenue','Springfield','IL','62704','US');
